require File.expand_path('../old_collaide.rb', __FILE__)
require File.expand_path('../domains.rb', __FILE__)
require File.expand_path('../document_type.rb', __FILE__)
require File.expand_path('../user.rb', __FILE__)
require File.expand_path('../document.rb', __FILE__)
