require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Advertisement::SaleBooksController do

  # This should return the minimal set of attributes required to create a valid
  # Advertisement::SaleBook. As you add validations to Advertisement::SaleBook, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Advertisement::SaleBooksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all advertisement_sale_books as @advertisement_sale_books" do
      sale_book = Advertisement::SaleBook.create! valid_attributes
      get :index, {}, valid_session
      assigns(:advertisement_sale_books).should eq([sale_book])
    end
  end

  describe "GET show" do
    it "assigns the requested advertisement_sale_book as @advertisement_sale_book" do
      sale_book = Advertisement::SaleBook.create! valid_attributes
      get :show, {:id => sale_book.to_param}, valid_session
      assigns(:advertisement_sale_book).should eq(sale_book)
    end
  end

  describe "GET new" do
    it "assigns a new advertisement_sale_book as @advertisement_sale_book" do
      get :new, {}, valid_session
      assigns(:advertisement_sale_book).should be_a_new(Advertisement::SaleBook)
    end
  end

  describe "GET edit" do
    it "assigns the requested advertisement_sale_book as @advertisement_sale_book" do
      sale_book = Advertisement::SaleBook.create! valid_attributes
      get :edit, {:id => sale_book.to_param}, valid_session
      assigns(:advertisement_sale_book).should eq(sale_book)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Advertisement::SaleBook" do
        expect {
          post :create, {:advertisement_sale_book => valid_attributes}, valid_session
        }.to change(Advertisement::SaleBook, :count).by(1)
      end

      it "assigns a newly created advertisement_sale_book as @advertisement_sale_book" do
        post :create, {:advertisement_sale_book => valid_attributes}, valid_session
        assigns(:advertisement_sale_book).should be_a(Advertisement::SaleBook)
        assigns(:advertisement_sale_book).should be_persisted
      end

      it "redirects to the created advertisement_sale_book" do
        post :create, {:advertisement_sale_book => valid_attributes}, valid_session
        response.should redirect_to(Advertisement::SaleBook.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved advertisement_sale_book as @advertisement_sale_book" do
        # Trigger the behavior that occurs when invalid params are submitted
        Advertisement::SaleBook.any_instance.stub(:save).and_return(false)
        post :create, {:advertisement_sale_book => {}}, valid_session
        assigns(:advertisement_sale_book).should be_a_new(Advertisement::SaleBook)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Advertisement::SaleBook.any_instance.stub(:save).and_return(false)
        post :create, {:advertisement_sale_book => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested advertisement_sale_book" do
        sale_book = Advertisement::SaleBook.create! valid_attributes
        # Assuming there are no other advertisement_sale_books in the database, this
        # specifies that the Advertisement::SaleBook created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Advertisement::SaleBook.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => sale_book.to_param, :advertisement_sale_book => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested advertisement_sale_book as @advertisement_sale_book" do
        sale_book = Advertisement::SaleBook.create! valid_attributes
        put :update, {:id => sale_book.to_param, :advertisement_sale_book => valid_attributes}, valid_session
        assigns(:advertisement_sale_book).should eq(sale_book)
      end

      it "redirects to the advertisement_sale_book" do
        sale_book = Advertisement::SaleBook.create! valid_attributes
        put :update, {:id => sale_book.to_param, :advertisement_sale_book => valid_attributes}, valid_session
        response.should redirect_to(sale_book)
      end
    end

    describe "with invalid params" do
      it "assigns the advertisement_sale_book as @advertisement_sale_book" do
        sale_book = Advertisement::SaleBook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Advertisement::SaleBook.any_instance.stub(:save).and_return(false)
        put :update, {:id => sale_book.to_param, :advertisement_sale_book => {}}, valid_session
        assigns(:advertisement_sale_book).should eq(sale_book)
      end

      it "re-renders the 'edit' template" do
        sale_book = Advertisement::SaleBook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Advertisement::SaleBook.any_instance.stub(:save).and_return(false)
        put :update, {:id => sale_book.to_param, :advertisement_sale_book => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested advertisement_sale_book" do
      sale_book = Advertisement::SaleBook.create! valid_attributes
      expect {
        delete :destroy, {:id => sale_book.to_param}, valid_session
      }.to change(Advertisement::SaleBook, :count).by(-1)
    end

    it "redirects to the advertisement_sale_books list" do
      sale_book = Advertisement::SaleBook.create! valid_attributes
      delete :destroy, {:id => sale_book.to_param}, valid_session
      response.should redirect_to(advertisement_sale_books_url)
    end
  end

end
